### ISSUE TITLE
Where do I specify the soundtrack name?

### ISSUE THREAD

**Issue by MajorXMidge** [obskyr/khinsider#13] opened 2017-04-07 23:58 UTC
I feel like such an idiot for asking this as I'm pretty sure the answer is obvious, but I cannot for the life of me find where to put it and I've been trying everything for the past hour, I just can't manage to find how to do it.

**Comment by obskyr** [comment] 2017-04-08 21:20
You run it from the command line (also known as the "terminal", "command window", or "command prompt")! If you've never had to use the command line, I can absolutely see how it's not obvious at all.

Assuming you're on Windows, the steps are as following:

1. Open the folder where you put khinsider.py
2. Hold shift and right-click in the folder
3. In the context menu, select "Open command window here" or something along those lines
4. In the black window with white text that appears, type a command as in the readme and press enter.

In this case, the command is `khinsider.py soundtrack-id` - just type that in, substituting what you want to download (or search for) for `soundtrack-id`.

Let me know how it goes!

**Comment by obskyr** [comment] 2017-05-08 20:56
@MajorXMidge How's it hanging?

**Comment by obskyr** [comment] 2017-05-31 09:49
@MajorXMidge I'll go ahead and close this issue, I suppose - hope you managed to get it working. If not, you can write here anytime! I'll answer even if the issue is closed.

**Closed by obskyr** 2017-05-31 09:49 UTC

**Comment by MajorXMidge** [comment] 2017-07-11 20:11
Sorry about the extremely long reply time, I had lots of things going on like coursework around that time so i wasn't able to reply, and I forgot about this until just now.

Anyway whenever I try to open the file in the command prompt, and when I put the ID of the OST I want. For example "C:\khinsider-master >khinsider.py pokemon-black-and-white", it says that there is no soundtrack specified.
