### ISSUE TITLE
Script can't download or search.

### ISSUE THREAD

**Issue by matpower123** [obskyr/khinsider#11] opened 2016-11-16 05:00 UTC
Hey, I've been using your script for a while (it's really great btw, thanks!), but as I tried to use it today after a long time, I can't get it to work at all.

I downloaded the latest version from the GitHub's repo as of today (11/16/2016) and I always get the same error message, it doesn't matter if I:
1) Try to use it with just the URL name
2) Try to use it with URL + Folder
3) Try to use it to search

[Here's a screenshot of my last attempt at trying to get it to work.](http://imgur.com/sJBFn90)
I'm using Python v3.5.2 x86 and pip did download the necessary dependencies required by the script.

[I'm attempting to get it from this URL](http://downloads.khinsider.com/game-soundtracks/album/devil-survivor-overclock). I also tried a few others just in case and I get the same behavior not matter what I do.

**Comment by obskyr** [comment] 2016-11-16 09:34
Hmm. That's odd. I cloned the repo afresh, ran it on both Python 2.7.12 and 3.5.2 with the same parameters, and no problems occurred. Here's my result:

![](https://cloud.githubusercontent.com/assets/4363779/20341348/307f7f10-abe6-11e6-8f04-4a8a49ff8851.png)

Seeing as I'm using the same Python version as you are, and I'm on x86 Windows, I'm fairly certain it's not an issue with the script or even Python. Probably something in your configuration went wrong somehow. Let's see if we can fix it, though!

If you run the commands:

```bat
> assoc .py
> ftype Python.File
```

What output do you get?

**Comment by matpower123** [comment] 2016-11-16 17:17
Okay, there is indeed something wrong with my setup. 
![Output](http://i.imgur.com/PrfXZnD.png)
Since it's in Portuguese, I guess I should translate what it means. `assoc` says that I don't have an association for .py while `ftype` tells me that it can't find Python.File nor that it has an association too. It works fine if I manually call `python` like you asked me to.

(Also I'm sorry, I actually tried to manually call for `python` before reporting this, but I used `python3` instead and of course, it didn't work.)

**Comment by obskyr** [comment] 2016-11-16 17:32
Whaaaaat! If `assoc` tells you there's no association, running just `khinsider.py` shouldn't work at all. I really don't know what's up with your setup, then. You might want to try right clicking a Python script, choosing "open with", and setting Python as default. If that doesn't work, I found a [few links](http://superuser.com/questions/362063/how-to-associate-a-file-with-a-program-in-windows-via-cmd) that [might help](http://eli.thegreenplace.net/2010/12/14/problem-passing-arguments-to-python-scripts-on-windows). Hope you manage to sort it out - it's a really weird issue!

**Comment by matpower123** [comment] 2016-11-16 17:39
Funnily enough, it does seem to have an association on the GUI, the .py has the Python logo and runs if I click on it. Well, thanks for the help! I'll try to solve this issue and give a read to your links.

I have a feeling that this is related to the fact I installed Python3 and uninstalled Python2 a few days ago, it shouldn't be too hard to fix.

**Comment by obskyr** [comment] 2016-11-16 17:43
I'll go ahead and close this issue then. Still, if you have anymore questions, feel free to ask! I'll answer even if the issue is closed.

**Closed by obskyr** 2016-11-16 17:43 UTC
