### ISSUE TITLE
Tried downloading Star Fox SNES OST

### ISSUE THREAD

**Issue by LyraKeaton** [obskyr/khinsider#50] opened 2020-07-12 20:00 UTC
Traceback (most recent call last):File "C:\Users\Robin\Desktop\khinsider\khinsider.py", line 589, in <module>sys.exit(doIt())File "C:\Users\Robin\Desktop\khinsider\khinsider.py", line 533, in doItsuccess = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)File "C:\Users\Robin\Desktop\khinsider\khinsider.py", line 408, in downloadreturn Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)File "C:\Users\Robin\Desktop\khinsider\khinsider.py", line 323, in downloadfiles.append(getAppropriateFile(song, formatOrder))File "C:\Users\Robin\Desktop\khinsider\khinsider.py", line 168, in getAppropriateFilereturn song.files[0]IndexError: list index out of range

**Comment by obskyr** [comment] 2022-04-12 05:45
Closing this as I can't reproduce it – it was most likely a temporary error. Feel free to comment if you'd like it reopened!

**Closed by obskyr** 2022-04-12 05:45 UTC
