### ISSUE TITLE
reported error

### ISSUE THREAD

**Issue by kiliancody** [obskyr/khinsider#48] opened 2020-04-24 21:10 UTC
An unexpected error occurred! If it isn't too much to ask, please report to http
s://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\khinsider\khinsider-master\khinsider.py", li
ne 589, in <module>
    sys.exit(doIt())
  File "C:\Users\User\Downloads\khinsider\khinsider-master\khinsider.py", li
ne 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=Tru
e)
  File "C:\Users\User\Downloads\khinsider\khinsider-master\khinsider.py", li
ne 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbos
e)
  File "C:\Users\User\Downloads\khinsider\khinsider-master\khinsider.py", li
ne 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "C:\Users\User\Downloads\khinsider\khinsider-master\khinsider.py", li
ne 168, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

**Comment by obskyr** [comment] 2020-04-30 15:54
Which exact command is resulting in this? I can't reproduce with a randomly selected soundtrack.

**Comment by daviddavo** [comment] 2020-05-01 09:16
`beet ydl "https://youtu.be/dQw4w9WgXcQ"`, for example, but it happens with every video.
If I delete the config, I get a 403 error

**Comment by obskyr** [comment] 2020-05-01 09:58
Hmm. Are you in the wrong repository, perchance? That seems to be a different program!

**Comment by AzuzoraDev** [comment] 2020-05-01 14:55
The same error occurs for me as well.
`Traceback (most recent call last):
  File "C:\Users\syntic139\Music\khinsider-master\khinsider-master\khinsider.py", line 589, in <module>
    sys.exit(doIt())
  File "C:\Users\syntic139\Music\khinsider-master\khinsider-master\khinsider.py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\syntic139\Music\khinsider-master\khinsider-master\khinsider.py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\syntic139\Music\khinsider-master\khinsider-master\khinsider.py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "C:\Users\syntic139\Music\khinsider-master\khinsider-master\khinsider.py", line 168, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range`

**Comment by obskyr** [comment] 2020-05-01 15:04
@AzuzoraDev With what soundtrack – what command, exactly?

**Comment by AzuzoraDev** [comment] 2020-05-01 15:18
`C:\Users\syntic139\Music\khinsider-master\khinsider.py mario-kart-8-full-gamerip`

**Comment by CrowTrain** [comment] 2020-05-05 06:13
This issue is occurring for me as well.

`khinsider.py ghostsoul-online` (as an example)

the error it gives me is

An unexpected error occurred! If it isn't too much to ask, please report to http
s://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "C:\Users\CrowTrain\My Documents\khinsider-master\khinsider-master\khinsider.
py", line 589, in <module>
    sys.exit(doIt())
  File "C:\Users\CrowTrain\My Documents\khinsider-master\khinsider-master\khinsider.
py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=Tru
e)
  File "C:\Users\CrowTrain\My Documents\khinsider-master\khinsider-master\khinsider.
py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbos
e)
  File "C:\Users\CrowTrain\My Documents\khinsider-master\khinsider-master\khinsider.
py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "C:\Users\CrowTrain\My Documents\khinsider-master\khinsider-master\khinsider.
py", line 168, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

**Comment by obskyr** [comment] 2020-05-05 09:28
Hmm. Those commands seem to work just fine for me. Are you on the latest version of the script? This seems similar to the error that was fixed in the latest version – try re-downloading the script, perhaps.

**Comment by fantasynoff** [comment] 2020-06-03 02:47
i think it's not woking at all
all of them are 'Couldn't download xxxxxx. Trying again...'

**Comment by AzuzoraDev** [comment] 2020-06-10 01:23
Unzip it to a new place, and make sure it is the latest version. Works for me after I just placed in a fresh place. (I just run it from batch with args). I didn't change anything though so perhaps it was a error on kh-side temporary.

**Comment by fantasynoff** [comment] 2020-06-11 23:54
thanks,today i tried with same directory, it's' worked✅

**Comment by obskyr** [comment] 2022-04-12 05:45
Closing this as it seems to be more or less solved. Feel free to comment if you'd like it reopened!

**Closed by obskyr** 2022-04-12 05:45 UTC
