### ISSUE TITLE
Escape 'release on' URLs

### ISSUE THREAD

**Issue by nobody-65534** [obskyr/khinsider#40] opened 2019-12-12 02:30 UTC
The URLs in the webpage section `Released on: Android   iOS   Windows ` should not be matched, or some html files would be downloaded.

**Comment by obskyr** [comment] 2019-12-12 02:32
Could you provide a command that triggers this bug?

**Comment by vtdiep** [comment] 2019-12-12 10:56
Hi, this is my first time commenting so apologies if anything is amiss.

I think that the issue is that soundtracks that have been released on multiple consoles have links to those console pages, and those links are being accepted as image links.
For example, "sonic-adventure-2-original-sound-track" has links to 5 consoles, which results in 5 extra html files being downloaded:
![image](https://user-images.githubusercontent.com/42816933/70705251-8d4d3a00-1c88-11ea-9b48-83b98154be90.png)

I think changing https://github.com/obskyr/khinsider/blob/00453f11e03dcb8eb92baba526990dc0f995976b/khinsider.py#L294 to `urls = [a['href'] for a in anchors if a.find("img") is not None]` should solve the issue

**Comment by obskyr** [comment] 2019-12-13 01:01
Thanks for the example! Perfect fix, too, @vtdiep.
Fixed in the latest version coming in a few seconds!

**Closed** 2019-12-13 01:01 UTC
